version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor:
      name: node/default
      tag: '18.16'
    steps:
      - checkout             
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: node server  
          name: Start server
      - run:
          command: sleep 5 && curl -I localhost:5000
          name: Verify server is running

workflows:
  build_and_test_app:
    jobs:
      - build_and_test